# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21bf8852340079df5eb806cf270aad6cca9bdd98c8db256d6c37adaf8493270d50e28a6b050643ae23c96d593a856a03c58d4f4b98526c61bd2461d6a0b0d8f0

test:
  secret_key_base: 63a07b0858f7cf9d51f480a80e8c3e5a8c3bf17fe1b16f62be31c82e6522a2d07538cbd28fd4ce3a646ec799e10b0caaa0f4b84e5ffa4f7d57123f57ace32ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
